apiVersion: v1
kind: ConfigMap
metadata:
  name: time-link-grid-env
  labels:
    app: time-link-grid
data:
  VITE_NODE1_LABEL: "My Dashboard"
  VITE_NODE1_URL: "https://dashboard.mycompany.com"
  VITE_NODE2_LABEL: "Analytics"
  VITE_NODE2_URL: "https://analytics.mycompany.com"
  VITE_NODE3_LABEL: "Monitoring"
  VITE_NODE3_URL: "https://monitoring.mycompany.com"
  VITE_NODE4_LABEL: "Documentation"
  VITE_NODE4_URL: "https://docs.mycompany.com"
  VITE_NODE5_LABEL: "Support"
  VITE_NODE5_URL: "https://support.mycompany.com"
  VITE_NODE6_LABEL: "Admin Panel"
  VITE_NODE6_URL: "https://admin.mycompany.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-link-grid
  labels:
    app: time-link-grid
spec:
  replicas: 3
  selector:
    matchLabels:
      app: time-link-grid
  template:
    metadata:
      labels:
        app: time-link-grid
    spec:
      containers:
        - name: app
          image: time-link-grid:latest
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: time-link-grid-env
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: time-link-grid-service
  labels:
    app: time-link-grid
spec:
  selector:
    app: time-link-grid
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: time-link-grid-ingress
  labels:
    app: time-link-grid
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: time-link-grid.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: time-link-grid-service
                port:
                  number: 80